# Generated by Django 3.0.4 on 2020-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='m_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
